/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type EmailAddress = string;
export type Datetime = string;
export type InternalActor = UserActor | MachineUserActor | SystemActor;
export type CustomerGroupMemberships = CustomerGroupMembership[];
export type Actor = UserActor | MachineUserActor | SystemActor | CustomerActor;
export type IssueTypeIcon = string;
export type IssueStatus = "OPEN" | "RESOLVED";
export type EmailActor =
  | UserActor
  | CustomerActor
  | {
      actorType: "supportEmailAddress";
      supportEmailAddress: string;
    }
  | {
      actorType: "deletedCustomer";
      customerId: Id;
    };
export type Component =
  | ComponentText
  | ComponentPlainText
  | ComponentSpacer
  | ComponentDivider
  | ComponentLinkButton
  | ComponentBadge
  | ComponentCopyButton
  | ComponentRow
  | ComponentContainer;
export type ComponentTextSize = "S" | "M" | "L";
export type ComponentTextColor = "NORMAL" | "MUTED" | "SUCCESS" | "WARNING" | "ERROR";
export type ComponentPlainTextSize = "S" | "M" | "L";
export type ComponentPlainTextColor = "NORMAL" | "MUTED" | "SUCCESS" | "WARNING" | "ERROR";
export type ComponentSpacerSize = "XS" | "S" | "M" | "L" | "XL";
export type ComponentDividerSpacingSize = "XS" | "S" | "M" | "L" | "XL";
export type ComponentBadgeColor = "GREY" | "GREEN" | "YELLOW" | "RED" | "BLUE";
export type ComponentRowContent =
  | ComponentText
  | ComponentPlainText
  | ComponentSpacer
  | ComponentDivider
  | ComponentLinkButton
  | ComponentBadge
  | ComponentCopyButton;
export type ComponentContainerContent =
  | ComponentText
  | ComponentPlainText
  | ComponentSpacer
  | ComponentDivider
  | ComponentLinkButton
  | ComponentBadge
  | ComponentCopyButton
  | ComponentRow;
export type CustomerGroupChangedPayload =
  | {
      changeType: "ADDED";
      eventType: "customer.customer_group_changed";
      customerGroup: CustomerGroup;
    }
  | {
      changeType: "UPDATED";
      eventType: "customer.customer_group_changed";
      customerGroup: CustomerGroup;
      previousCustomerGroup: CustomerGroup;
    }
  | {
      changeType: "REMOVED";
      eventType: "customer.customer_group_changed";
      previousCustomerGroup: CustomerGroup;
    };
export type ThreadStatus = "TODO" | "DONE" | "SNOOZED";
export type ThreadStatusDetail =
  | {
      type: "CREATED";
      createdAt: string | string | unknown;
    }
  | {
      type: "SNOOZED";
      snoozedAt: string | string | unknown;
      snoozedUntil: string | string | unknown;
    }
  | {
      type: "UNSNOOZED";
      snoozedAt: string | string | unknown;
    }
  | {
      type: "NEW_REPLY";
      newReplyAt: string | string | unknown;
    }
  | {
      type: "LINK_LINEAR_UPDATED";
      updatedAt: string | string | unknown;
      linearIssueId: string;
    };
export type ThreadAssignee =
  | User
  | MachineUser
  | {
      id:
        | "customer_status_state_machine"
        | "thread_status_state_machine"
        | "timeline_writer"
        | "timeline_listener"
        | "email_builder"
        | "email_sender"
        | "postmark_external_inbound_handler"
        | "postmark_inbound_handler"
        | "email_inbound_handler"
        | "notifications"
        | "slack_integrations_janitor"
        | "slack_notifications_sender"
        | "slack_webhook_handler"
        | "customer_authentication"
        | "unread_user_chat_messages_handler"
        | "unread_user_chat_messages_publisher"
        | "plain_cli"
        | "public_event_builder"
        | "webhook_subscription_handler"
        | "slack_user_notification_builder"
        | "slack_workspace_notification_builder"
        | "discord_workspace_notification_builder"
        | "backfill_external_email_settings_job"
        | "customer_card_updater"
        | "internal_customer_card_api"
        | "linear_webhook_handler"
        | "linear_integrations_janitor"
        | "job"
        | "search_indexer"
        | "thread_snooze_handler"
        | "timeline_events_writer"
        | "thread_triage_handler";
    };

/**
 * Webhook request
 */
export interface WebhooksSchemaDefinition {
  timestamp: unknown;
  workspaceId: Id;
  payload:
    | CustomerStatusTransitionedPayload
    | CustomerChangedPayload
    | CustomerGroupMembershipsChangedPayload
    | TimelineEntryChangedPayload
    | CustomerGroupChangedPayload
    | ThreadCreatedPublicEventPayload
    | ThreadStatusTransitionedPublicEventPayload
    | ThreadAssignmentTransitionedPublicEventPayload
    | ThreadEmailReceivedPublicEventPayload
    | ThreadEmailSentPublicEventPayload
    | ThreadLabelsChangedPublicEventPayload
    | ThreadPriorityChangedPublicEventPayload
    | ThreadChatSentPublicEventPayload
    | CustomerCreatedPublicEventPayload
    | CustomerUpdatedPublicEventPayload
    | CustomerDeletedPublicEventPayload;
  id: Id;
  type:
    | "thread.thread_created"
    | "thread.thread_status_transitioned"
    | "thread.thread_assignment_transitioned"
    | "thread.email_received"
    | "thread.email_sent"
    | "thread.chat_sent"
    | "thread.note_created"
    | "thread.thread_labels_changed"
    | "thread.thread_priority_changed"
    | "customer.customer_created"
    | "customer.customer_updated"
    | "customer.customer_deleted"
    | "customer.customer_status_transitioned"
    | "customer.customer_changed"
    | "customer.customer_group_changed"
    | "customer.customer_group_memberships_changed"
    | "timeline.timeline_entry_changed";
  webhookMetadata: {
    webhookTargetId: Id;
    webhookDeliveryAttemptId: Id;
    webhookDeliveryAttemptNumber: number;
    webhookDeliveryAttemptTimestamp: Datetime;
  };
}
/**
 * The status of a customer has changed
 */
export interface CustomerStatusTransitionedPayload {
  eventType: "customer.customer_status_transitioned";
  previousCustomer: Customer;
  customer: Customer;
}
export interface Customer {
  id: Id;
  email: Email;
  externalId: string | null;
  fullName: string;
  shortName: string | null;
  assignedAt: Datetime | null;
  assignedToUser: User | null;
  status: "IDLE" | "ACTIVE" | "SNOOZED";
  statusChangedAt: Datetime;
  markedAsSpamAt?: Datetime | null;
  markedAsSpamBy?: InternalActor | null;
  customerGroupMemberships: CustomerGroupMemberships;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
export interface Email {
  email: EmailAddress;
  isVerified: boolean;
  verifiedAt: Datetime | null;
}
export interface User {
  id: Id;
  email: EmailAddress;
  fullName: string;
  publicName: string;
  status: "ONLINE" | "OFFLINE" | "BREAK";
  statusChangedAt: Datetime;
  createdAt: Datetime;
  createdBy: InternalActor;
  updatedAt: Datetime;
  updatedBy: InternalActor;
  deletedAt: Datetime | null;
  deletedBy: InternalActor | null;
}
export interface UserActor {
  actorType: "user";
  userId: Id;
}
export interface MachineUserActor {
  actorType: "machineUser";
  machineUserId: Id;
}
export interface SystemActor {
  actorType: "system";
  system:
    | "customer_status_state_machine"
    | "thread_status_state_machine"
    | "timeline_writer"
    | "timeline_listener"
    | "email_builder"
    | "email_sender"
    | "postmark_external_inbound_handler"
    | "postmark_inbound_handler"
    | "email_inbound_handler"
    | "notifications"
    | "slack_integrations_janitor"
    | "slack_notifications_sender"
    | "slack_webhook_handler"
    | "customer_authentication"
    | "unread_user_chat_messages_handler"
    | "unread_user_chat_messages_publisher"
    | "plain_cli"
    | "public_event_builder"
    | "webhook_subscription_handler"
    | "slack_user_notification_builder"
    | "slack_workspace_notification_builder"
    | "discord_workspace_notification_builder"
    | "backfill_external_email_settings_job"
    | "customer_card_updater"
    | "internal_customer_card_api"
    | "linear_webhook_handler"
    | "linear_integrations_janitor"
    | "job"
    | "search_indexer"
    | "thread_snooze_handler"
    | "timeline_events_writer"
    | "thread_triage_handler";
}
export interface CustomerGroupMembership {
  customerId: Id;
  customerGroupId: Id;
  workspaceId: Id;
  createdAt: Datetime;
  createdBy: InternalActor;
  updatedAt: Datetime;
  updatedBy: InternalActor;
  customerGroup: CustomerGroup;
}
export interface CustomerGroup {
  id: Id;
  workspaceId: Id;
  name: string;
  key: string;
  color: string;
  createdAt: Datetime;
  createdBy: InternalActor;
  updatedAt: Datetime;
  updatedBy: InternalActor;
}
export interface CustomerActor {
  actorType: "customer";
  customerId: Id;
}
/**
 * A customer has been created or updated
 */
export interface CustomerChangedPayload {
  changeType: "ADDED" | "UPDATED";
  eventType: "customer.customer_changed";
  customer: Customer;
  previousCustomer: Customer | null;
}
export interface CustomerGroupMembershipsChangedPayload {
  eventType: "customer.customer_group_memberships_changed";
  changeType: "ADDED" | "REMOVED";
  customer: Customer1;
  previousCustomer: Customer1;
}
export interface Customer1 {
  id: Id;
  email: Email;
  externalId: string | null;
  fullName: string;
  shortName: string | null;
  markedAsSpamAt?: Datetime | null;
  markedAsSpamBy?: InternalActor | null;
  customerGroupMemberships: CustomerGroupMemberships;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
/**
 * A timeline entry has been added, updated or removed
 */
export interface TimelineEntryChangedPayload {
  eventType: "timeline.timeline_entry_changed";
  /**
   * null if changeType=ADDED
   */
  previousTimelineEntry: TimelineEntry | null;
  /**
   * null if changeType=REMOVED
   */
  timelineEntry: TimelineEntry | null;
  changeType: "ADDED" | "UPDATED" | "REMOVED";
}
export interface TimelineEntry {
  id: Id;
  customerId: Id;
  timestamp: Datetime;
  actor: Actor;
  entry:
    | IssueStatusTransitionedEntry
    | IssueTypeChangedEntry
    | IssuePriorityChangedEntry
    | IssueDeletedEntry
    | NoteEntry
    | CustomerAssignmentTransitionedEntry
    | ChatEntry
    | CustomerStatusTransitionedEntry
    | EmailEntry
    | CustomEntry
    | LinearIssueLinkStateTransitionedEntry;
}
export interface IssueStatusTransitionedEntry {
  entryType: "issue_status_transitioned";
  issueId: Id;
  issueKey: string;
  issueTypeId: Id;
  issueTypePublicName: string;
  issueTypeIcon: IssueTypeIcon | null;
  priority: IssuePriority;
  previousStatus: IssueStatus | null;
  nextStatus: IssueStatus;
}
export interface IssuePriority {
  value: number;
  label: string;
}
export interface IssueTypeChangedEntry {
  entryType: "issue_issue_type_changed";
  issueId: Id;
  issueKey: string;
  previousIssueTypeId: Id;
  previousIssueTypePublicName: string;
  previousIssueTypeIcon: IssueTypeIcon | null;
  nextIssueTypeId: Id;
  nextIssueTypePublicName: string;
  nextIssueTypeIcon: IssueTypeIcon | null;
  status: IssueStatus;
  priority: IssuePriority;
}
export interface IssuePriorityChangedEntry {
  entryType: "issue_priority_changed";
  issueId: Id;
  issueKey: string;
  issueTypeId: Id;
  issueTypePublicName: string;
  issueTypeIcon: IssueTypeIcon | null;
  previousPriority: IssuePriority;
  nextPriority: IssuePriority;
  status: IssueStatus;
}
export interface IssueDeletedEntry {
  entryType: "issue_deleted";
  issueId: Id;
  issueKey: string;
  issueTypeId: Id;
  issueTypePublicName: string;
  issueTypeIcon: IssueTypeIcon | null;
  status: IssueStatus;
  priority: IssuePriority;
}
export interface NoteEntry {
  entryType: "note";
  noteId: Id;
  text: string;
  markdown: string | null;
}
export interface CustomerAssignmentTransitionedEntry {
  entryType: "customer_assignment_transitioned";
  previousUserId: Id | null;
  previousUser: User | null;
  nextUserId: Id | null;
  nextUser: User | null;
}
export interface ChatEntry {
  entryType: "chat";
  chatId: Id;
  text: string | null;
  attachments: ChatEntryAttachment[];
  customerReadAt: Datetime | null;
}
export interface ChatEntryAttachment {
  id: Id;
  fileName: string;
  fileSizeBytes: number;
  fileMimeType: string;
  fileExtension: string | null;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
  type: "CHAT";
}
export interface CustomerStatusTransitionedEntry {
  entryType: "customer_status_transitioned";
  previousStatus: "IDLE" | "ACTIVE" | "SNOOZED";
  nextStatus: "IDLE" | "ACTIVE" | "SNOOZED";
}
export interface EmailEntry {
  entryType: "email";
  emailId: Id;
  to: EmailParticipant;
  from: EmailParticipant;
  additionalRecipients: EmailParticipant[];
  hiddenRecipients: EmailParticipant[];
  subject: string | null;
  textContent: string | null;
  hasMoreTextContent: boolean;
  markdownContent: string | null;
  hasMoreMarkdownContent: boolean;
  authenticity: "PASS" | "FAIL" | "UNKNOWN";
  sentAt: Datetime | null;
  receivedAt: Datetime | null;
  attachments: EmailEntryAttachment[];
  inReplyToEmailId: string | null;
  isStartOfThread: boolean;
}
export interface EmailParticipant {
  email: string;
  name: string | null;
  emailActor: EmailActor | null;
}
export interface EmailEntryAttachment {
  id: Id;
  fileName: string;
  fileSizeBytes: number;
  fileMimeType: string;
  fileExtension: string | null;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
  type: "EMAIL";
  emailContentId: string;
}
export interface CustomEntry {
  entryType: "custom";
  externalId: string | null;
  title: string;
  type: string | null;
  /**
   * @minItems 1
   */
  components: [Component, ...Component[]];
  attachments: CustomEntryAttachment[];
}
export interface ComponentText {
  type: "text";
  textSize: ComponentTextSize | null;
  textColor: ComponentTextColor | null;
  text: string;
}
export interface ComponentPlainText {
  plainTextSize: ComponentPlainTextSize | null;
  plainTextColor: ComponentPlainTextColor | null;
  plainText: string;
  type: "plainText";
}
export interface ComponentSpacer {
  spacerSize: ComponentSpacerSize;
  type: "spacer";
}
export interface ComponentDivider {
  dividerSpacingSize: ComponentDividerSpacingSize | null;
  type: "divider";
}
export interface ComponentLinkButton {
  linkButtonUrl: string;
  linkButtonLabel: string;
  type: "linkButton";
}
export interface ComponentBadge {
  badgeLabel: string;
  badgeColor: ComponentBadgeColor | null;
  type: "badge";
}
export interface ComponentCopyButton {
  copyButtonValue: string;
  copyButtonTooltipLabel: string | null;
  type: "copyButton";
}
export interface ComponentRow {
  type: "row";
  /**
   * @minItems 1
   */
  rowMainContent: [ComponentRowContent, ...ComponentRowContent[]];
  rowAsideContent: ComponentRowContent[];
}
export interface ComponentContainer {
  type: "container";
  /**
   * @minItems 1
   */
  containerContent: [ComponentContainerContent, ...ComponentContainerContent[]];
}
export interface CustomEntryAttachment {
  id: Id;
  fileName: string;
  fileSizeBytes: number;
  fileMimeType: string;
  fileExtension: string | null;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
  type: "CUSTOM_TIMELINE_ENTRY";
}
export interface LinearIssueLinkStateTransitionedEntry {
  entryType: "linear_issue_link_state_transitioned";
  customerId: Id;
  issueId: Id;
  issueKey: string;
  issueTypeId: Id;
  issueTypePublicName: string;
  linearIssueId: string;
  previousLinearStateId: string;
  nextLinearStateId: string;
}
export interface ThreadCreatedPublicEventPayload {
  eventType: "thread.thread_created";
  thread: Thread;
}
export interface Thread {
  id: Id;
  customer: Customer1;
  title: string;
  previewText?: string | null;
  priority: number;
  externalId: string | null;
  status: ThreadStatus;
  statusChangedAt: Datetime | null;
  statusChangedBy?: Actor | null;
  statusDetail: ThreadStatusDetail | null;
  assignee: ThreadAssignee | null;
  assignedAt: Datetime | null;
  labels: Label[];
  firstInboundMessageInfo: ThreadMessageInfo | null;
  firstOutboundMessageInfo: ThreadMessageInfo | null;
  lastInboundMessageInfo: ThreadMessageInfo | null;
  lastOutboundMessageInfo: ThreadMessageInfo | null;
  supportEmailAddresses: string[];
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
export interface MachineUser {
  id: Id;
  fullName: string;
  publicName: string;
  description: string | null;
  createdAt: Datetime;
  createdBy: InternalActor;
  updatedAt: Datetime;
  updatedBy: InternalActor;
  deletedAt: Datetime | null;
  deletedBy: InternalActor | null;
}
export interface Label {
  id: Id;
  labelType: LabelType;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
export interface LabelType {
  id: Id;
  name: string;
  icon?: string | null;
  isArchived?: boolean;
  archivedAt: Datetime | null;
  archivedBy: InternalActor | null;
  createdAt: Datetime;
  createdBy: InternalActor;
  updatedAt: Datetime;
  updatedBy: InternalActor;
}
export interface ThreadMessageInfo {
  timestamp: string | string | unknown;
  messageSource: "CHAT" | "EMAIL" | "API" | "SLACK";
}
export interface ThreadStatusTransitionedPublicEventPayload {
  eventType: "thread.thread_status_transitioned";
  previousThread: Thread;
  thread: Thread;
}
export interface ThreadAssignmentTransitionedPublicEventPayload {
  eventType: "thread.thread_assignment_transitioned";
  previousThread: Thread;
  thread: Thread;
}
export interface ThreadEmailReceivedPublicEventPayload {
  eventType: "thread.email_received";
  thread: Thread;
  email: Email1;
}
export interface Email1 {
  timelineEntryId: Id;
  id: Id;
  to: EmailParticipant;
  from: EmailParticipant;
  replyTo: string | null;
  additionalRecipients: EmailParticipant[];
  hiddenRecipients: EmailParticipant[];
  subject: string | null;
  textContent: string | null;
  markdownContent: string | null;
  authenticity: "PASS" | "FAIL" | "UNKNOWN";
  sentAt: Datetime | null;
  receivedAt: Datetime | null;
  attachments: Attachment[];
  inReplyToEmailId: string | null;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
export interface Attachment {
  id: Id;
  fileName: string;
  fileSizeBytes: number;
  fileMimeType: string;
  fileExtension: string | null;
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
export interface ThreadEmailSentPublicEventPayload {
  eventType: "thread.email_sent";
  thread: Thread;
  email: Email1;
}
export interface ThreadLabelsChangedPublicEventPayload {
  eventType: "thread.thread_labels_changed";
  changeType: "ADDED" | "REMOVED";
  thread: Thread;
  previousThread: Thread;
}
export interface ThreadPriorityChangedPublicEventPayload {
  eventType: "thread.thread_priority_changed";
  previousThread: Thread;
  thread: Thread;
}
export interface ThreadChatSentPublicEventPayload {
  eventType: "thread.chat_sent";
  chat: Chat;
  thread: Thread;
}
export interface Chat {
  timelineEntryId: Id;
  id: Id;
  customerReadAt: Datetime | null;
  text?: string | null;
  attachments: Attachment[];
  createdAt: Datetime;
  createdBy: Actor;
  updatedAt: Datetime;
  updatedBy: Actor;
}
/**
 * A customer has been created
 */
export interface CustomerCreatedPublicEventPayload {
  eventType: "customer.customer_created";
  customer: Customer1;
}
/**
 * A customer has been updated
 */
export interface CustomerUpdatedPublicEventPayload {
  eventType: "customer.customer_updated";
  customer: Customer1;
  previousCustomer: Customer1;
}
/**
 * A customer has been deleted
 */
export interface CustomerDeletedPublicEventPayload {
  eventType: "customer.customer_deleted";
  previousCustomer: Customer1;
}
