fragment ActorParts on Actor {
  ... on UserActor {
    ...UserActorParts
  }
  ... on CustomerActor {
    ...CustomerActorParts
  }
  ... on SystemActor {
    ...SystemActorParts
  }
  ... on MachineUserActor {
    ...MachineUserActorParts
  }
  ... on DeletedCustomerActor {
    ...DeletedCustomerActorParts
  }
}
