fragment CompanyParts on Company {
  __typename
  id
  name
  domainName
  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...InternalActorParts
  }
  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...InternalActorParts
  }
}
