fragment CustomerParts on Customer {
  __typename
  id
  fullName
  shortName
  externalId
  email {
    email
    isVerified
    verifiedAt {
      ...DateTimeParts
    }
  }
  company {
    ...CompanyParts
  }
  updatedAt {
    ...DateTimeParts
  }
  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...InternalActorParts
  }
  markedAsSpamAt {
    ...DateTimeParts
  }
}
