fragment CustomerEventParts on CustomerEvent {
  __typename
  id
  customerId
  title
  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...ActorParts
  }
  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...ActorParts
  }
}
