fragment CustomerTenantMembershipParts on CustomerTenantMembership {
  __typename
  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...InternalActorParts
  }
  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...InternalActorParts
  }
  tenant {
    ...TenantParts
  }
}
