fragment IssueParts on Issue {
  __typename
  id
  issueKey
  status
  customer {
    id
  }
  priority {
    ...IssuePriorityParts
  }
  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...ActorParts
  }
  createdBy {
    ...ActorParts
  }
  createdAt {
    ...DateTimeParts
  }
  issueType {
    ...IssueTypeParts
  }
  deletedAt {
    ...DateTimeParts
  }
}
