fragment LabelParts on Label {
  __typename
  id

  labelType {
    ...LabelTypeParts
  }

  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...ActorParts
  }

  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...ActorParts
  }
}
