fragment ThreadParts on Thread {
  __typename
  id
  ref
  externalId
  customer {
    id
  }

  status
  statusDetail {
    ...ThreadStatusDetailParts
  }
  statusChangedAt {
    ...DateTimeParts
  }

  title
  description
  previewText
  priority
  tenant {
    ...TenantParts
  }

  labels {
    ...LabelParts
  }
  threadFields {
    ...ThreadFieldParts
  }
  assignedAt {
    ...DateTimeParts
  }
  assignedTo {
    ...ThreadAssigneeParts
  }

  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...ActorParts
  }

  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...ActorParts
  }
}
