fragment ThreadEventParts on ThreadEvent {
  id
  threadId
  title
  components {
    ...EventComponentParts
  }
  createdAt {
    ...DateTimeParts
  }
  createdBy {
    ...ActorParts
  }
  updatedAt {
    ...DateTimeParts
  }
  updatedBy {
    ...ActorParts
  }
}
