fragment TierMembershipParts on TierMembership {
  __typename
  ... on TenantTierMembership {
    ...TenantTierMembershipParts
  }
  ... on CompanyTierMembership {
    ...CompanyTierMembershipParts
  }
}
