query customers(
  $filters: CustomersFilter
  $sortBy: CustomersSort
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  customers(
    filters: $filters
    sortBy: $sortBy
    first: $first
    after: $after
    last: $last
    before: $before
  ) {
    edges {
      node {
        ...CustomerParts
      }
    }
    pageInfo {
      ...PageInfoParts
    }
    totalCount
  }
}
