query issues(
  $filters: IssuesFilter
  $sortBy: IssuesSort
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  issues(
    filters: $filters
    sortBy: $sortBy
    first: $first
    after: $after
    last: $last
    before: $before
  ) {
    edges {
      node {
        ...IssueParts
      }
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
