query labelTypes(
  $filters: LabelTypeFilter
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  labelTypes(filters: $filters, first: $first, after: $after, last: $last, before: $before) {
    edges {
      cursor
      node {
        ...LabelTypeParts
      }
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
