query searchTenants(
  $searchQuery: TenantsSearchQuery!
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  searchTenants(
    searchQuery: $searchQuery
    first: $first
    after: $after
    last: $last
    before: $before
  ) {
    edges {
      cursor
      node {
        tenant {
          ...TenantParts
        }
      }
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
