query threadFieldsByThreadId(
  $threadId: ID!
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  thread(threadId: $threadId) {
    threadFields(first: $first, after: $after, last: $last, before: $before) {
      edges {
        cursor
        node {
          ...ThreadFieldParts
        }
      }
      pageInfo {
        ...PageInfoParts
      }
    }
  }
}
