query tiers($first: Int, $after: String, $last: Int, $before: String) {
  tiers(first: $first, after: $after, last: $last, before: $before) {
    edges {
      cursor
      node {
        ...TierParts
      }
    }
    pageInfo {
      ...PageInfoParts
    }
  }
}
