name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: GraphQL Mutation Filenames
        uses: batista/lint-filenames@v1.0.1
        with:
          path: './src/graphql/mutations'
          pattern: '[a-z]+((\\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?'
      - name: GraphQL Query Filenames
        uses: batista/lint-filenames@v1.0.1
        with:
          path: './src/graphql/queries'
          pattern: '[a-z]+((\\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?'
      - name: Fragment Filenames
        uses: batista/lint-filenames@v1.0.1
        with:
          path: './src/graphql/fragments'
          pattern: '[a-z]+((\\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?Parts.gql$'
